# Generated by Django 2.0.5 on 2018-05-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('gen_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=6, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='gen_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Keys'),
        ),
        migrations.AddField(
            model_name='patients',
            name='gen_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Keys'),
        ),
    ]
