# Generated by Django 2.0.5 on 2018-05-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180506_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='gen_id',
            new_name='gen',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='gen_id',
            new_name='gen',
        ),
    ]
