# Generated by Django 2.0.5 on 2018-05-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180507_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='gen',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='gen',
        ),
        migrations.DeleteModel(
            name='Keys',
        ),
    ]
