# Generated by Django 2.0.5 on 2018-05-11 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intakes',
            fields=[
                ('intake_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_taken', models.TimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('presc_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('notes', models.TextField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_modified', models.DateField(default=django.utils.timezone.now)),
                ('is_purchased', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('sched_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('day', models.CharField(max_length=10)),
                ('medicine', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_modified', models.DateField(default=django.utils.timezone.now)),
                ('presc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Prescriptions')),
            ],
        ),
        migrations.AddField(
            model_name='intakes',
            name='sched',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Schedules'),
        ),
    ]
