# Generated by Django 2.0.5 on 2018-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180515_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
