# Generated by Django 2.0.5 on 2018-05-16 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180515_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakes',
            name='time_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
